spring:
  cloud:
    gateway:
      routes:
        #        - id: test_rout
        #          #满足断言去哪?
        #          uri: https://www.baidu.com
        #          #断言数组 ：多个规则
        #          predicates:
        #            - Query=url,baidu
        #
        #        - id: qq_rout
        #            #满足断言去哪?
        #          uri: https://www.qq.com
        #            #断言数组 ：多个规则
        #          predicates:
        #            - Query=url,qq
        - id: waiguagg_route
          #lb 代表负载均衡
          uri: lb://one-waiguagg
          predicates:
            #按照日期之后转发
            #- After=2023-02-23T14:20:00.000+08:00[Asia/Shanghai]
            #按照cookie
            #- Cookie=loginname, ruoyi
            #按照header正则规则
            #- Header=token,^(?!\d+$)[\da-zA-Z]+$
            #host转发
            #- Host=**.baidu.com
            #请求方式
            #- Method=POST
            #请求路径转发
            #- Path=/system/config/{segment}
            #参数转发  参数必须是token值必须是整数
            #- Query=token, \d+
            #请求ip地址转发   请求是ip
            #- RemoteAddr=192.168.1.1/0

            #按照路径断言 http
            - Path=/api/waiguagg/**
            - Vip=accept-encoding,br
          filters:
            #过滤掉api前缀 使得后端服务只需要处理剩下的路径部分(剩下的需要跟接口路径匹配)
            - RewritePath=/api/waiguagg/(?<segment>.*),/$\{segment}
            - OnceToken=ont-token,jwt

        - id: third_party_route
          uri: lb://one-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: fileServer_route
          #lb 代表负载均衡
          uri: lb://one-fileServer
          predicates:
            #按照路径断言 http
            - Path=/api/fileServer/**
          filters:
            #过滤掉api前缀
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: waigua_search_route

          uri: lb://one-search
          predicates:
            - Path=/one-search/**
          filters:
            #过滤掉api前缀
            - RewritePath=/one-search/(?<segment>.*),/$\{segment}


        - id:  waigua_auth_route
          #lb 代表负载均衡
          uri: lb://one-auth-server
          predicates:
            #按照路径断言 http
            - Path=/one-auth-server/**
          filters:
            - AddRequestHeader=handle-server, one-auth-server
            #过滤掉api前缀
            - RewritePath=/one-auth-server/(?<path>.*),/$\{path}

        - id: admin_route
          uri:
            lb://one-admin
          predicates:
            #按照路径断言 http
            - Path=/one-admin/**
          filters:
            - AddRequestHeader=handle-server, one-admin
            #过滤掉api前缀
            - RewritePath=/one-admin/(?<segment>.*),/$\{segment}


#        - id:  waigua_order_route
#          #lb 代表负载均衡
#          uri: lb://one-order
#          predicates:
#            #按照路径断言 http
#            - Path=/one-order/**
#          filters:
#            - AddRequestHeader=handle-server, one-order
#            #过滤掉api前缀
#            - RewritePath=/one-order/(?<path>.*),/$\{path}


#        - id: admin_route
#          #lb 代表负载均衡
#          uri: lb://renren-fast
#          predicates:
#            #按照路径断言 http
#            - Path=/api/**
#          filters:
#            #过滤掉api前缀
#            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}


#        - id: waigua_host_route
#          uri: lb://one-waiguagg
#          predicates:
#            - Host=waiguattt.com
