##配置数据源
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: one-search
  thymeleaf:
    cache: false
#配置端口号
server:
  port: 40000
logging:
  level:
    com.ttt.one.waiguagg: debug