ttt.user.name=aaa
ttt.user.age=11
#spring.cache.type=redis
spring.session.store-type=redis
#env
spring.profiles.active=dev 

spring.rabbitmq.host=47.104.177.6
spring.rabbitmq.port=5672
spring.rabbitmq.virtual-host=/
#\u5F00\u542F\u53D1\u9001\u7AEF \u786E\u8BA4
spring.rabbitmq.publisher-confirm-type=correlated
#\u5F00\u542F\u53D1\u9001\u7AEF \u6D88\u606F\u62B5\u8FBE\u961F\u5217\u7684 \u786E\u8BA4
spring.rabbitmq.publisher-returns=true
#\u53EA\u8981\u62B5\u8FBE\u961F\u5217\uFF0C\u4EE5\u5F02\u6B65\u53D1\u9001\u4F18\u5148\u56DE\u8C03\u6211\u4EEC\u8FD9\u4E2Areturnconfirm
spring.rabbitmq.template.mandatory=true
#\u6D88\u8D39\u7AEF\u624B\u52A8\u7B7E\u6536ack\u6D88\u606F
spring.rabbitmq.listener.simple.acknowledge-mode=manual


spring.cloud.sentinel.transport.dashboard=localhost:8333
spring.cloud.sentinel.transport.port=8719

management.endpoints.web.exposure.include=*

logging.level.org.springframework.cloud.openfeign=debug
logging.level.org.springframework.cloud.sleuth=debug

#\u670D\u52A1\u8FFD\u8E2A
#spring.zipkin.base-url=http://192.168.56.10:9411/
#spring.zipkin.discovery-client-enabled=false
#spring.zipkin.sender.type=web
#spring.sleuth.sampler.probability=1

#logback
plumelog.appName=plumelog_demo
plumelog.redisHost=47.104.177.6
plumelog.redisPort=6379
#plumelog.redisAuth=plumelogredis
#spring.profiles.active=dev

##log4j
#log4j.rootLogger=INFO
#log4j.appender.stdout=org.apache.log4j.ConsoleAppender
#log4j.appender.stdout.Target=System.out
#log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
#log4j.appender.stdout.layout.ConversionPattern=[%-5p] %d{yyyy-MM-dd HH:mm:ss,SSS} [%c.%t]%n%m%n
###redis\u505A\u4E3A\u4E2D\u95F4\u4EF6
#log4j.appender.L=com.plumelog.log4j.appender.RedisAppender
#log4j.appender.L.appName=plumelog
#log4j.appender.L.env=${spring.profiles.active}
#log4j.appender.L.redisHost=192.168.56.10:6379
##redis\u6CA1\u6709\u5BC6\u7801\u8FD9\u4E00\u9879\u4E3A\u7A7A\u6216\u8005\u4E0D\u9700\u8981
##log4j.appender.L.redisAuth=123456