spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.113:8848
    alicloud:
      sms:
        host: http://dingxin.market.alicloudapi.com
        path: /dx/sendSms
        appcode: 9ed2bc748bdf471599d8b2cd7b16eeba
        tpl_id: TP1711063

  application:
    name: one-third-party

server:
  port: 33333